### ISSUE TITLE
User can search for exercises

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/ajax-project#1]
## 💰 Motivation

Users should be able to search for exercises

## 📐 Plan

Add a search bar that lets users type in their desired body part they would like to workout and get exercises back.

## 🖼️ Wireframes

![user can search mobile](https://user-images.githubusercontent.com/24307282/192338793-cb21a004-0abe-45fe-9ddc-7baa3c8cbe6a.png)
![user can search desktop](https://user-images.githubusercontent.com/24307282/192338877-518746e3-f192-4fc4-b88a-8161bbaf0e7d.png)

## ✅ Task List

Mobile
- [x] Create a nav bar to show the name of the app
- [x] Create a second nav bar below the main one with the text "upcoming workouts"
- [x] Create a plus icon on the top nav bar on the right side of the name of the app
- [x] When the plus icon is clicked show a model with title text "WORKOUT"
- [x] Add an input-box and search-button to the modal
- [x] If there are no workouts, below the second nav bar have the text "No exercises upcoming..."

Desktop
- [x] Create a nav bar to show the name of the app
- [x] Create a second nav bar below the main one
- [x] Add text for "upcoming workouts" and "new exercises" on the second nav bar and associate the text with changes to view
- [x] Highlight either "upcoming workouts" or "new exercises" text depending on which view the user is on
- [x] Change the view when the user clicks on the unlighted text on the second nav bar
- [x] In the "upcoming workouts" view add a plus-icon on the top nav bar to switch to the "new exercises" view when clicked
- [x] Switch the plus icon with a search-button and input-box when in the "new exercises" view
- [x] If there are no workouts, below the second nav bar have the text "No exercises upcoming..." in the "upcoming workouts" view
