### ISSUE TITLE
User can see results of search

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/ajax-project#2]
## 💰 Motivation

Users should be able to see the exercises they search for.

## 📐 Plan

Populate the page with exercises from the wger API database when the user searches.

## 🖼️ Wireframes

![user can see results of search mobile](https://user-images.githubusercontent.com/24307282/192339098-d4c673b8-ead0-4b08-a8e9-d85e5db519a1.png)
![user can see results of search desktop](https://user-images.githubusercontent.com/24307282/192339158-c93ce92e-f390-4964-abf8-da09dd3d5d40.png)

## ✅ Task List

Occurs after user clicks on search box, enters in body part to be worked out, and hits enter or clicks search button

- [x] Grab string that user entered into input box and save it in a variable
- [x] Create two functions to house two different API requests for images search and exercise search
- [x] In both functions make XMLHttpRequest objects
- [x] In the function that retrieves exercise info set the query to the string that the user entered into the search
- [x] Show each exercise with the information from the database and default image
- [x] Take the name of each exercise and call the image API function to query for the exercise name
- [x] As the images come in, change the search results to the higher quality images
- [x] Populate the modal or page with the results of the search for the user to view
- [x] When the user hits enter in the search box again, remove all preexisting items before repopulating.
