### ISSUE TITLE
User can see info about exercises

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/ajax-project#3]
## 💰 Motivation

Users should be able to get detailed descriptions of exercises to know how to do them.

## 📐 Plan

Add a button on each exercise that accesses exercise descriptions from the wger API database.

## 🖼️ Wireframes

![User can see exercise info mobile](https://user-images.githubusercontent.com/24307282/192339619-ee133b28-7fc2-439b-a35d-a93387b94af0.png)
![User can see exercise info desktop](https://user-images.githubusercontent.com/24307282/192339656-33ad621c-dcc7-4dde-8413-3b8e1329ad5f.png)

## ✅ Task List

- [x] Add info button or icon to each of the search results
- [x] Style button and icon to match design
- [x] When info button is clicked have modal appear
- [x] Style modal to match design
- [x] Add functionality to close modal with red "X" button
- [x] Add functionality to close modal with clicks not within the modal
- [x] Add description and title from wger database to a storage that lasts while the search result is there
- [x] Take description from that storage and use it as paragraph text in the modal
- [x] Take title from storage and use it as title of modal
- [x] Reset the storage on a new search
