### ISSUE TITLE
User can add exercises to days of the week

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/ajax-project#4]
## 💰 Motivation

User should be able to save the exercises they search for on the day they plan to take action on that exercise.

## 📐 Plan

Add an icon on each exercise that is searched which allows the workout to be saved. Add a date selector for that search so the user can add multiple workouts to one day.

## 🖼️ Wireframes

![User can add workout to day mobile](https://user-images.githubusercontent.com/24307282/192339943-0b0325b0-8200-4542-8b48-c657b5cfb657.png)
![User can add workout to day desktop](https://user-images.githubusercontent.com/24307282/192339949-9e41af6f-3fcb-4707-bd84-8e0fa64409f9.png)

## ✅ Task List

Mobile
- [x] Add an input with a type attribute value of date to the workout search modal with the text "DATE"
- [x] Add a button with the text "ADD" to the workout search modal
- [x] When the user clicks on date have a date selector appear that is on the current day
- [x] After the user selects their desired date, make the color of the date button green
- [x] Listen for clicks from the user on the items returned by the search
- [x] If a user clicks a search item, turn the border color to green
- [x] Once the user has selected at least one exercise, make the ADD button appear available
- [x] If the user clicks the ADD button then push the selected exercises to a data object and to upcoming workouts
- [x] In upcoming workouts show the workouts from today first and all later dates subsequently
- [x] If the user tries to pick a date before today, make them choose a date in the future

Desktop
- [x] Add a plus icon to each of the search results on the page
- [x] Add a date input on the second nav bar
- [x] If the user has not selected a date, grey out the search results
- [x] If the user has not selected a date, make the date border a red color
- [x] If the user clicks on a plus icon change the date and item border color to green
- [x] Save the green search result item to a data object
- [x] Push the added items to the page
- [x] Push a break between items that groups them by the date
- [x] If the workout is for today then put "Today" text on the break above those exercises
- [x] Use days of the week after "Today" and "Tomorrow" have been used
- [x] Use dates if further than 6 days in the future
- [x] Give each saved exercise a unique id
