### ISSUE TITLE
User can delete exercises

### ISSUE THREAD

**Issue by jacobhusband** [jacobhusband/ajax-project#5]
## 💰 Motivation

Users should be able to remove exercises from their upcoming workouts.

## 📐 Plan

Add a delete button on each exercises that will remove the exercise if the user clicks it.

## 🖼️ Wireframes

![User can delete exercises mobile](https://user-images.githubusercontent.com/24307282/192340152-7f61dfa9-7927-47da-aa21-5344bc273e11.png)
![User can delete exercises desktop](https://user-images.githubusercontent.com/24307282/192340155-6852c067-46a0-41c7-b836-d872c292c6b4.png)

## ✅ Task List

- [x] Add a red x image icon from figma into vscode
- [x] Inside the function that creates the mobile version of upcoming workout elements, add the red x icon
- [x] Add a red x image button from figma into vscode
- [x] Inside the function that creates the desktop version of upcoming workout elements, add the red x button
- [x] When a user clicks on the red x icon, remove the item from the desktop and mobile DOM as well as the data object
- [x] When a user clicks on the red x button, remove the item from the desktop and mobile DOM as well as the data object
